# -*- coding: utf-8 -*-
"""Phase 3 assembly for slate 0918. Copies BOARD_SHELL_2.html and fills its
placeholders. The shell's CSS and markup are not touched; the slate table
header cells already carry the seven v4 columns from an earlier v4 run."""
import io, re

shell = io.open("BOARD_SHELL_2.html", encoding="utf-8").read()

DATE = "Friday 18 September 2026"
HEADLINE = ("Six of tonight&rsquo;s ten clubs are run by a coach who was not in charge in May, "
            "and one of them took the job on Monday")
STANDFIRST = ("Five fixtures, one from each of Europe&rsquo;s top five leagues, parsed from the typed sheet "
              "slate.5.xlsx &mdash; all five cards built at full T1 depth, then revised against the "
              "confirmed team sheets, benches and injury lists.")
COMPETITIONS = ("Bundesliga matchday 4 &middot; Serie A giornata 5 &middot; Ligue 1 journ&eacute;e 5 &middot; "
                "Premier League matchweek 5 &middot; LaLiga jornada 7")

OVERVIEW = """<p>The single structural fact across this card is how much of it was assembled in July. <strong>Six of the ten clubs have a head coach who was not in charge when last season ended</strong>: Mauro Lustrinelli took Union Berlin on 1 July, Ivan Juric took Monza on 1 July, Alberto Aquilani replaced Fabio Grosso at Sassuolo, Xabi Alonso took Chelsea on 1 July after being appointed in mid-May, Mart&iacute;n Anselmi took Elche on 13 June after Eder Sarabia stepped down of his own accord in late May, and Lens have had three coaches this calendar year &mdash; Pierre Sage left for Crystal Palace, Dino Toppm&ouml;ller was appointed on 16 June and dismissed on Monday 15 September, and <strong>Yannick Cahuzac takes charge of a Ligue 1 match for the first time tonight</strong>. Only Bayern, Brentford, Monaco and Espanyol start under the man who finished 2025&ndash;26. <strong>An earlier version of this board named Sarabia as Elche&rsquo;s coach and reported him suspended from the bench, on the word of a Spanish preview. That was wrong, it is corrected on the card rather than quietly removed, and it is the one factual error this board made.</strong></p>
<p>The second fact is where the money went, because it landed on exactly the positions the research spec weights. <strong>Chelsea banked over &pound;425m in sales &mdash; a club record &mdash; sold Enzo Fern&aacute;ndez on deadline day without signing the replacement, and paid &pound;117m for Morgan Rogers</strong>. Sassuolo sold their centre-back to Leeds for &euro;40m, their centre-forward to Lazio and their goalkeeper, and replaced all three. Monaco sold Maghnes Akliouche for &euro;50m and Aladji Bamba for &euro;35.5m. Lens sold Mamadou Sangar&eacute; to Brentford for a Brentford club record, and Elche sold &Aacute;lvaro Rodr&iacute;guez for &euro;25m and David Affengruber for &euro;12m. Union Berlin replaced all four senior centre-backs for &euro;3m between them, and Monza came up through the Serie B play-off and borrowed six defenders. Four of tonight&rsquo;s ten clubs will field a centre-back pairing that did not exist in May.</p>
<p>The third is that every division on the board is scoring above its own 2025&ndash;26 rate, some of them far above. <strong>The Bundesliga is at 3.85 goals per match against 3.24 last season and 81.5% over 2.5 against 63.7%; Serie A is at 3.02 against 2.43; LaLiga 3.05 against 2.69; the Premier League 2.85 against 2.75. Ligue 1 alone is flat, at 2.75 against 2.82 &mdash; and it is producing 27.8% home wins and 36.1% draws against 46.1% home wins last season.</strong> Those samples run from 27 matches to 59. Each strip therefore carries two baselines, and on several rows the gap between the two baselines is wider than the gap between the two clubs.</p>
<p>The confirmed team sheets, which arrived after the cards were written, settled four of the five questions each card had named as the one most likely to change its ratings, and settled three of them against the side already carrying the thinner evidence. <strong>Union are without both Friedrich and Nsoki, so two of the four centre-backs they bought this summer do not play and a third is a substitute. Chelsea are without Moises Ca&iuml;cedo and Jo&atilde;o Pedro, with Romeo Lavia only on the bench, so a midfield that had already sold Enzo Fern&aacute;ndez and Andrey Santos starts Jordan Henderson and Valent&iacute;n Barco. Yannick Cahuzac&rsquo;s first Lens team is a 4-2-3-1 that keeps the structure rather than reverting, with Sk&oacute;ra&#347;, Hazard and Ivanovi&#263; all in reserve.</strong> Only the Serie A card&rsquo;s open question &mdash; a published Serie A record for Daniele Perenzoni &mdash; is untouched by a team sheet. Three of the summer&rsquo;s largest signings across the board start on the bench: Bayern&rsquo;s two &euro;50m arrivals and Brentford&rsquo;s club-record midfielder.</p>
<div class="note"><strong>Structural consequence.</strong> The Asian handicap is Dangerous on all five cards, because four of the five fixtures contain a side whose margin evidence is four matches old or produced under a different coach, and the fifth contains a 0&ndash;5. The 1X2 is Dangerous on three and only OK on the two where one club&rsquo;s record is genuinely continuous. BTTS is the best-supported family on the board &mdash; Well-suited on three cards and OK on the other two &mdash; because clean-sheet and failed-to-score rates are the series every one of these divisions publishes in full for both seasons. Totals follow it. Discipline and corners carry the widest spreads: discipline is Well-suited where the official has a long published record against a high-fouling side and Dangerous where he has five top-flight matches, and corners are Well-suited where a club&rsquo;s surplus holds across two seasons and Dangerous where it halved with no mechanism behind it.</div>"""

rows = [
 ("20:30", "Germany &middot; Bundesliga MD4", "Bayern M&uuml;nchen &ndash; Union Berlin",
  "Allianz Arena, M&uuml;nchen", "Benjamin Brand", "4 &middot; 4 (3 &middot; 3 league)", "new manager, away side"),
 ("20:45", "Italy &middot; Serie A G5", "Monza &ndash; Sassuolo",
  "U-Power Stadium, Monza", "Daniele Perenzoni", "6 &middot; 6 (4 &middot; 4 league)", "promoted side"),
 ("20:45", "France &middot; Ligue 1 J5", "AS Monaco &ndash; RC Lens",
  "Stade Louis-II, Monaco", "Cl&eacute;ment Turpin", "4 &middot; 4 league", "interim manager, first match"),
 ("21:00", "England &middot; Premier League MW5", "Brentford &ndash; Chelsea",
  "Gtech Community Stadium, London", "Andy Madley", "5 &middot; 5 (4 &middot; 4 league)", "new coach, record sales"),
 ("21:00", "Spain &middot; LaLiga J7", "RCD Espanyol &ndash; Elche CF",
  "RCDE Stadium, Barcelona", "Jon Ander Gonz&aacute;lez Esteban", "6 &middot; 6 league", "referee new to Primera"),
]
SLATE_ROWS = "\n      ".join(
    "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>" % r
    for r in rows)

PROVENANCE_NOTE = """<div class="note"><strong>Evidence.</strong> No number on this board was supplied to me and none was estimated. Club rates for both seasons were computed match by match from ESPN&rsquo;s public match record &mdash; results for goals, over 2.5, BTTS, clean sheets and failed-to-score; per-match boxscores for corners, fouls, cards, shots and possession; key-event periods for first-half goals &mdash; and cross-checked against each club&rsquo;s ESPN season statistics object. Expected goals, non-penalty xG, PPDA and deep completions come from Understat for both seasons and every club. <strong>League baselines are in baselines_0918.md</strong>: the 2025&ndash;26 lines are carried unchanged from baselines_0917.md and cost no search, and the 2026&ndash;27 lines were computed the same way over every completed match of this season &mdash; 27 in the Bundesliga, 40 in Serie A, 36 in Ligue 1, 40 in the Premier League, 59 in LaLiga. The Bundesliga figures reproduce the line already in baselines_0917.md from an independent FotMob count, which is why this board trusts the method. <strong>Fields unpublished across the slate:</strong> a penalty rate for all five referees, in every source reached; ESPN&rsquo;s 2025&ndash;26 xG for any club, which is why last season&rsquo;s xG is Understat throughout; xG of any kind for Monza&rsquo;s 2025&ndash;26, because Serie B publishes none and none was modelled; fees for most of Monza&rsquo;s twelve arrivals and for Espanyol&rsquo;s six loans; any fee at all in Chelsea&rsquo;s own window review, so every Chelsea figure here is press-reported. <strong>Last season standing in for a thin current sample:</strong> nowhere in full &mdash; every strip carries both columns side by side with the match count in brackets &mdash; but the 26/27 column is three matches per club at Bayern&ndash;Union and four at the Serie A, Ligue 1 and Premier League fixtures, and should be read as such. <strong>Contradictions, and what the team sheets settled.</strong> Resolved by the confirmed lists: Friedrich and Nsoki are both out for Union and Imeri is fit; Takumi Minamino is fit and a substitute, which ends the cruciate-or-muscle dispute in the least severe direction; Jonathan Gradit is fit enough for the Lens bench; the LaLiga fixture is at the RCDE Stadium, as the fixture record said and one preview denied. Still unresolved and named on the cards: whether Chris Bedia joined or left Union; whether Paul Pogba signed for Monaco or was released by it on 19 August; Monaco&rsquo;s net transfer balance. <strong>One thing the team sheets did not resolve but corrected: Elche&rsquo;s head coach is Mart&iacute;n Anselmi, appointed 13 June 2026, not Eder Sarabia. The card said Sarabia and said he was suspended from the bench. Both were wrong.</strong> New absences the previews missed: Ansu Fati (calf) for Monaco and Yeferson Paz for Sassuolo.</div>"""

NAV_LINKS = "\n    ".join(
    '<a href="#f%d">%s<span>%s &middot; %s</span></a>' % (i + 1, r[2], r[0], r[3].split(",")[0])
    for i, r in enumerate(rows))

FIXTURES = "\n\n".join(
    io.open("fx_0918_f%d.html" % i, encoding="utf-8").read().rstrip() for i in range(1, 6))

CLOSING = """<ul>
<li><strong>Best structurally supported today: BTTS.</strong> Well-suited on <strong>Monza&ndash;Sassuolo</strong> (eight league matches between the two clubs this season, eight both-teams-to-score, no clean sheet and no blank for either), on <strong>Brentford&ndash;Chelsea</strong> (Chelsea four from four this season on top of 63.2% across 38 last), and on <strong>Espanyol&ndash;Elche</strong> (Elche 83.3% this season and 71.1% last, with failed-to-score rates of 16.7% and 13.2%, the lowest on the board). OK on the other two. It is the only family that is Dangerous nowhere, because clean-sheet and failed-to-score series are published in full by all five divisions for both seasons.</li>
<li><strong>Next best: totals.</strong> Well-suited on <strong>Bayern&ndash;Union</strong>, where the Bundesliga&rsquo;s 3.85 goals and 81.5% over 2.5 sit on top of Bayern&rsquo;s 94.1% across 34 matches last season and three from three for Union, and on <strong>Brentford&ndash;Chelsea</strong>, where Chelsea have gone over in all four this season after 65.8% in 38. OK on the other three, in each case because the two clubs&rsquo; own rates disagree or one of them was set in a different division.</li>
<li><strong>Least supported: the Asian handicap and draw-no-bet, Dangerous on all five cards.</strong> Seven of the eight league matches played by Brentford and Chelsea finished within a goal or level; Monza and Sassuolo have the same pattern; Monaco sit second on 10 points with fewer shots and less xG than they concede while Lens sit tenth with the best chance-creation numbers on the board; Bayern&rsquo;s three league margins are +4, 0 and +1; and five of Elche&rsquo;s six matches were within a goal with the sixth a 0&ndash;5. <strong>The 1X2 is Dangerous on three</strong> &mdash; Monza&ndash;Sassuolo, Monaco&ndash;Lens and Brentford&ndash;Chelsea &mdash; and only OK on the two where one side&rsquo;s record is genuinely continuous.</li>
<li><strong>Widest spreads: discipline and corners.</strong> Discipline is <strong>Well-suited on Brentford&ndash;Chelsea</strong> (Brentford 15.5 fouls per match, Madley at 4.6 fouls per card this season, the Premier League the most heavily carded of the five divisions at 3.98) and <strong>on Espanyol&ndash;Elche</strong> (Espanyol 17.67 fouls, the highest on the board, LaLiga at 4.46 cards, the official steady at 4.45&ndash;4.70 across 71 matches), and <strong>Dangerous on Monza&ndash;Sassuolo</strong>, where Perenzoni has five Serie A matches in three seasons and a Serie B record from a division carrying 47% more cards. Corners are <strong>Well-suited on Bayern&ndash;Union and Monaco&ndash;Lens</strong>, where one club&rsquo;s surplus holds across both seasons with a visible mechanism, and <strong>Dangerous on Espanyol&ndash;Elche</strong>, where Espanyol&rsquo;s count has halved to 2.17 per match with their shots and possession unchanged.</li>
<li><strong>There is no normal fixture on this board.</strong> Every one of the five contains at least one club whose head coach was not in charge in May. The closest is <strong>Espanyol&ndash;Elche</strong>, where both clubs played in this division last season and both have six league matches already played &mdash; the deepest current sample here &mdash; but Elche changed coach in June, which is a correction to what this page first said. Everything else is a club that changed coach, changed division, or has three or four matches on the clock.</li>
<li><strong>Where the evidence is thinnest, and which part of the board to trust least.</strong> First, <strong>Bayern&ndash;Union</strong>: three league matches per club, the smallest sample on the slate, and each club&rsquo;s three contains one result that distorts every rate built on it &mdash; Bayern&rsquo;s 0&ndash;0 at Schalke and Union&rsquo;s 0&ndash;4 at Leverkusen, now compounded by both Friedrich and Nsoki being confirmed out. Second, <strong>the referees&rsquo; penalty rates, which are unpublished for all five officials</strong> in every source reached, so no Discipline row on this board can speak to contact in the box. Third, <strong>Monaco&ndash;Lens</strong>, where the away side&rsquo;s entire strip was produced under two coaches neither of whom picks the team tonight, and where the divisional home-win rate of 27.8% over 36 matches contradicts 46.1% over 306.</li>
<li><strong>What the confirmed team sheets changed, in one line per card.</strong> Bayern&ndash;Union: Neuer starts, closing the goalkeeping gap the card flagged, and Union&rsquo;s summer centre-back line is two out and one benched. Monza&ndash;Sassuolo: Monza name the eleven that was trailed; Aquilani resolves both selection questions the other way, with Bowie benched. Monaco&ndash;Lens: Monaco switch to a back three with Zakaria in it, Minamino and Salisu are fit substitutes, Ansu Fati is a new absence, and Cahuzac keeps the structure. Brentford&ndash;Chelsea: Ca&iuml;cedo and Jo&atilde;o Pedro out, Lavia benched, Chelsea in a 3-4-2-1, and Brentford&rsquo;s club-record signing starts on the bench. Espanyol&ndash;Elche: four of Espanyol&rsquo;s six summer loans are substitutes, Elche&rsquo;s injury list is one name, and the head coach on this card was wrong.</li>
</ul>"""

SOURCES = """Fixture list: the tab &ldquo;Slate 5&rdquo; inside slate.5.xlsx, read from the sheet XML (the workbook is strict-OOXML and opens as zero sheets in the normal reader); venue, kickoff and matchday confirmed against ESPN&rsquo;s public scoreboard for 18 September 2026. Club and league data: ESPN&rsquo;s public match record and season statistics objects for all five divisions and both seasons, plus ESPN&rsquo;s Serie B record for Monza&rsquo;s promotion campaign and a Serie B 2025&ndash;26 baseline computed over all 390 matches; Understat getLeagueData for xG, non-penalty xG, PPDA and deep completions. Referees: appointments from bundesliga.com and kicker (Brand), tuttomonza, forzamonza and sassuolonews (Perenzoni), lensois.com and horizonactu (Turpin), the Chelsea and Brentford club match pages (Madley), and iusport, lagrada and copeelche (Gonz&aacute;lez Esteban); records from playerstats.football profiles 507, 955, 208, 77 and 284, each of which independently listed tonight&rsquo;s fixture as that official&rsquo;s next appointment. Transfers and team news: fcbinside, sportschau and neunzigplus (Bayern, Union); madeinbrianza, lottomatica and sassuolonews (Monza, Sassuolo); maxifoot, dicodusport, lensois.com and befoot (Monaco, Lens); ESPN, the Yahoo and roundtable window reviews and chelseafc.com (Brentford, Chelsea); futbolfantasy (Espanyol, Elche); with previews from bundesliga.com, Sky Sport Italia, Sports Mole and comuniate. League baselines: baselines_0918.md, whose 2025&ndash;26 lines are carried from baselines_0917.md and baselines_0916.md. <strong>Confirmed team sheets, benches and injury lists for all five fixtures were supplied by you after the cards were written, and the Elche coaching change was then verified independently against TeleElx, Infobae, eldesmarque and the club&rsquo;s own announcement.</strong> Every source used is logged in full in sources_0918.md."""

out = shell
out = out.replace("{{DATE}}", DATE)
out = out.replace("<!--DATE-->", DATE)
out = out.replace("<!--HEADLINE-->", HEADLINE)
out = out.replace("<!--STANDFIRST-->", STANDFIRST)
out = out.replace("<!--COMPETITIONS-->", COMPETITIONS)
out = out.replace("<!--OVERVIEW-->", OVERVIEW)
out = out.replace("<!--SLATE_ROWS-->", SLATE_ROWS)
out = out.replace("<!--PROVENANCE_NOTE-->", PROVENANCE_NOTE)
out = out.replace("  <!--COMPLETION_NOTE-->\n", "")   # every fixture DONE at T1: omitted
out = out.replace("<!--COMPLETION_NOTE-->", "")
out = out.replace("<!--NAV_LINKS-->", NAV_LINKS)
out = out.replace("<!--FIXTURES-->", FIXTURES)
out = out.replace("<!--CLOSING-->", CLOSING)
out = out.replace("<!--SOURCES-->", SOURCES)

io.open("context-board_0918.html", "w", encoding="utf-8").write(out)
print("unfilled placeholders:", re.findall(r"<!--[A-Z_]+-->|\{\{[A-Z]+\}\}", out))
print("bytes:", len(out), "| fixture cards embedded:", out.count('<article class="fixture"'))
