# -*- coding: utf-8 -*-
"""Apply the confirmed team sheets, benches and injury lists supplied after
Phase 2 to the five fixture cards of slate 0918. Every replacement is
asserted, so a silent miss fails the run instead of half-patching a card."""
import io, sys

EDITS = {}

def E(fn, old, new):
    EDITS.setdefault(fn, []).append((old, new))

# ---------------------------------------------------------------- f1
E("fx_0918_f1.html",
  "<strong>Union: Oliver Burke (Achilles tendon), Andrik Markgraf (cruciate ligament, return not expected before March 2027), Andrej Ili&#263; (appendix surgery), Josip Juranovi&#263; (illness, and the first-choice right-sided defender this season) and Kastriot Imeri (thigh) are out</strong>; one of the two previews reached additionally lists Marvin Friedrich and Stanley Nsoki as unavailable, which would remove two of the four new centre-backs, and that is not corroborated by the other. No suspensions are reported for either side.</li>",
  "<strong>Union: Oliver Burke (Achilles tendon), Andrik Markgraf (knee), Andrej Ili&#263; (illness), Josip Juranovi&#263; (illness, and the first-choice right-sided defender this season) and &mdash; now confirmed &mdash; <em>both</em> Marvin Friedrich (wound) and Stanley Nsoki (muscle) are out</strong>. <strong>The contradiction flagged before kickoff has resolved against them playing: two of the four centre-backs Union bought this summer are unavailable, and a third, Zeno Van Den Bosch, is only on the bench.</strong> Kastriot Imeri, reported as a thigh absence in one preview, is in fact among the substitutes. No suspensions for either side; Bayern's only listed absence is Tom Bischof's team-mate Tarek Buchmann (knee).</li>")

E("fx_0918_f1.html",
  "<li><strong>Not sourced.</strong> Brand&rsquo;s penalty rate, and any club history; Bayern&rsquo;s first-choice goalkeeper after selling both deputies in one window &mdash; the ledger shows the departures and no arrival; a fee for Union&rsquo;s loan signings; whether Friedrich and Nsoki are actually out, which two previews disagree on.",
  "<li><strong>Not sourced.</strong> Brand&rsquo;s penalty rate, and any club history; a fee for Union&rsquo;s loan signings. <strong>Two gaps named before kickoff are now closed by the team sheets:</strong> Bayern&rsquo;s goalkeeper after selling both deputies is <strong>Manuel Neuer</strong>, with Jonas Urbig the substitute; and Friedrich and Nsoki are confirmed out.")

E("fx_0918_f1.html",
  "<li><strong>The single fact that would most change which family I choose is whether Marvin Friedrich and Stanley Nsoki play.</strong> Two of the four centre-backs Union bought this summer are listed as out by one preview and not by the other. A confirmed team sheet naming the back line &mdash; and whether it is the pair that has started the last two matchdays &mdash; would settle at once how much of the 2.91 xG against is the system and how much is absence, and that distinction is what separates the corner and total rows from the handicap and BTTS rows.</li>",
  "<li><strong>That question is now answered, and it answered the unfavourable way.</strong> The fact I named as most decisive &mdash; whether Friedrich and Nsoki play &mdash; is settled: both are out, and Van Den Bosch is a substitute, so Union defend with Querfeld and Uduokhai, one holdover and one &euro;1.5m signing, in front of Trimmel and Rothe as full-backs. That does not move the corner or total rows, which never depended on it; it widens the BTTS and handicap rows, because the 2.91 xG against now has to be read as a system <em>and</em> an absence at once, with no published figure separating them.</li>")

# ---------------------------------------------------------------- f2
E("fx_0918_f2.html",
  "<strong>Sassuolo are without Idzes, Pieragnolo, Boloca, Cand&eacute;, Kon&eacute;, Sebastian Walukiewicz and Volpato</strong> &mdash; Walukiewicz again being a summer signing, this time in the rebuilt centre-back line.",
  "<strong>Sassuolo are without Idzes (muscle), Pieragnolo (knee), Boloca (muscle), Cand&eacute; (knee), Kon&eacute; (a broken leg), Sebastian Walukiewicz (muscle), Volpato (thigh) and Yeferson Paz (knee)</strong> &mdash; eight, with Walukiewicz again a summer signing, this time in the rebuilt centre-back line.")

E("fx_0918_f2.html",
  "<strong>Sassuolo 4-3-3</strong> &mdash; Muri&#263;; Cinquegrano, &#268;aleta-Car, Leysen, Doig; Ad&#382;i&#263;, Mati&#263;, Thorstvedt; Berardi, Bowie, Lauriente, with Aquilani choosing between Thorstvedt and Bakola in midfield and Bowie and Esposito in attack.</li>",
  "<strong>Sassuolo 4-3-3</strong> &mdash; Muri&#263;; Cinquegrano, Leysen, &#268;aleta-Car, Doig; Thorstvedt, Mati&#263;, Bakola; Berardi, Esposito, Lauriente. <strong>Confirmed: Monza&rsquo;s eleven is exactly the one trailed, and Aquilani resolved both of his selection questions against the trailed pair &mdash; Bakola starts alongside Thorstvedt rather than instead of him, Esposito leads the line and Kieron Bowie, the loan signing from Verona, is a substitute, alongside Ad&#382;i&#263;, Dom&iacute;nguez, Obrador and Sulemana.</strong></li>")

# ---------------------------------------------------------------- f3
E("fx_0918_f3.html",
  "<strong>Monaco: Jordan Teze (muscular, rested), Mamadou Coulibaly (quadriceps, long-term), Anis Soubeir (ankle) and Takumi Minamino are out</strong> &mdash; Minamino's diagnosis is itself disputed between a cruciate injury and a muscle lesion, and that disagreement is in the source rather than resolved by it. <strong>Mohammed Salisu has recovered from a ruptured cruciate and was in the squad at Strasbourg.</strong>",
  "<strong>Monaco: Jordan Teze, Mamadou Coulibaly (muscle), Anis Soubeir, Saint-Mleux Idumbo (groin), Mika Biereth (listed inactive) and &mdash; new, and not in any preview reached &mdash; <strong>Ansu Fati, the &euro;11m summer signing, with a calf injury</strong>, are out.</strong> <strong>Takumi Minamino, whose diagnosis the previews disputed between a cruciate injury and a muscle lesion, is fit and among the substitutes, which settles that disagreement in the least severe direction. Mohammed Salisu is also on the bench, back from a ruptured cruciate.</strong>")

E("fx_0918_f3.html",
  "Saud Abdulhamid (a knock), Isma&euml;lo Ganiou and Jonathan Gradit, returning from a tibia-fibula fracture, are all doubts with the sources disagreeing on Gradit. No suspensions reported. Probable elevens: <strong>Monaco 4-2-3-1</strong> &mdash; Hr&aacute;decky; Vanderson, Dier, San&eacute;, Nazinho; Lamine Camara, Zakaria; Abline, Golovin, Detourbet; Brunner. <strong>Lens</strong> &mdash; Risser; Gradit, Ganiou, Todibo; Aguilar, Ha&iuml;dara, Bulatovi&#263;, Udol; Thauvin, Sima; Ivanovi&#263;.</li>",
  "<strong>Saud Abdulhamid is out too, with a contusion; Jonathan Gradit is fit enough for the bench, which settles the disagreement over his fracture return.</strong> No suspensions reported. <strong>Confirmed elevens &mdash; Monaco 3-4-2-1, not the 4-2-3-1 trailed</strong>: Hr&aacute;decky; Zakaria, Dier, San&eacute;; Vanderson, Lamine Camara, Diop, Nazinho; Golovin, Abline; Brunner &mdash; with Zakaria dropping into a back three and Detourbet a substitute. <strong>Lens 4-2-3-1</strong>: Risser; Aguilar, Antonio, Todibo, Udol; Ha&iuml;dara, Kadile; Soares, Cuisance, Thauvin; Sima. <strong>Lamine Camara, the midfielder Chelsea are reported to have targeted on deadline day before Monaco withdrew, starts in tonight&rsquo;s other fixture&rsquo;s subplot.</strong></li>")

E("fx_0918_f3.html",
  "<strong>The evidence for what Cahuzac's Lens will look like is zero matches</strong>, and that should be read literally rather than as a figure of speech.",
  "<strong>The evidence for what Cahuzac's Lens will look like was zero matches; it is now one team sheet.</strong> He has kept a 4-2-3-1 and picked continuity over the summer&rsquo;s recruitment: <strong>Sk&oacute;ra&#347; (&euro;6m), Hazard, Ivanovi&#263; and Gradit are all substitutes, and Abdoulaye Sima leads the line</strong> with Cuisance and Thauvin behind him. Todibo, the Aston Villa loanee, partners Antonio at centre-back. A shape is not a season, but it is no longer nothing.")

E("fx_0918_f3.html",
  "<li><strong>The single fact that would most change which family I choose is Cahuzac's first team sheet and shape.</strong> Nothing published yet says whether the interim keeps Toppm&ouml;ller's structure &mdash; which produced the best chance-creation numbers on this slate and the tenth position in the table &mdash; or reverts to something closer to Sage's second-placed side. A confirmed eleven and formation would tell me at once whether Lens's 2.76 xG per match is still the relevant number, and that is what separates the corner and team-goals rows from the first-half and result rows.</li>",
  "<li><strong>That question is now answered, and it answers in favour of the corner and team-goals rows.</strong> Cahuzac has named a 4-2-3-1 with Thauvin and Cuisance behind Sima and Todibo at centre-back &mdash; structural continuity with the side that produced 2.76 xG and 6.75 corners per match, not a reversion. <strong>The remaining unknown is no longer the shape but the bench: Sk&oacute;ra&#347;, Hazard and Ivanovi&#263; sitting out means the three summer attacking signings are all in reserve, so what changes after sixty minutes is less predictable than what starts.</strong> The first-half and result rows stay where they are, because one team sheet is still not a match played.</li>")

# ---------------------------------------------------------------- f4
E("fx_0918_f4.html",
  "<strong>Chelsea list Moises Ca&iuml;cedo (calf), Marco Palestra (fitness), Emmanuel Emegha (fitness) and Jordan Henderson (wrist) as doubts, and Jo&atilde;o Pedro's involvement is described by Alonso only as \"a possibility\"</strong> after he withdrew from the Brazil squad during the international break. No suspensions are reported for either side. Ca&iuml;cedo's absence would leave a midfield that has already lost Enzo Fern&aacute;ndez and Andrey Santos without its remaining first-choice holder. Predicted elevens: <strong>Brentford</strong> &mdash; Kelleher; Kayode, Schuster, Ajer, Lewis-Potter; Janelt, Sangar&eacute;; Schade, Yarmolyuk, Anthony; Thiago. <strong>Chelsea</strong> &mdash; Mart&iacute;nez; Fofana, Lacroix, Colwill; Neto, Lavia, James, Chavarria; Palmer, Jo&atilde;o Pedro, Rogers.</li>",
  "<strong>Chelsea are confirmed without Moises Ca&iuml;cedo, Jo&atilde;o Pedro, Emmanuel Emegha and Marco Palestra</strong> &mdash; both of the doubts that mattered have resolved against playing. <strong>Ca&iuml;cedo's absence leaves a midfield that had already lost Enzo Fern&aacute;ndez and Andrey Santos without its remaining first-choice holder, and Romeo Lavia is only a substitute: Chelsea start Jordan Henderson and Valent&iacute;n Barco in central midfield, and Danny Welbeck at centre-forward in place of Jo&atilde;o Pedro.</strong> Jordan Henderson starts against the club whose contract he terminated eight weeks ago. No suspensions for either side. <strong>Confirmed elevens &mdash; Brentford 4-2-3-1</strong>: Kelleher; Kayode, Schuster, Ajer, Lewis-Potter; Yarmoliuk, Janelt; Anthony, Damsgaard, Schade; Igor Thiago &mdash; with <strong>Mamadou Sangar&eacute;, the club-record signing, and El Hadji Malick Diouf, the &pound;35m defender, both on the bench</strong> alongside Callum Wilson. <strong>Chelsea 3-4-2-1</strong>: Mart&iacute;nez; Lacroix, Colwill, Chavarr&iacute;a; Neto, Henderson, Barco, Rogers; Palmer; Welbeck &mdash; a back three rather than the four trailed, with Est&ecirc;v&atilde;o, Gittens, Gusto, Hato, Lavia and Quenda in reserve. One name in the Chelsea eleven was not legible in the team-sheet graphic and is not guessed at here.</li>")

E("fx_0918_f4.html",
  "and Jo&atilde;o Pedro is only \"a possibility\" tonight</strong> &mdash; and the conceded halves of the family are better documented than the scored halves.",
  "and Jo&atilde;o Pedro is confirmed out, with Danny Welbeck leading the line instead</strong> &mdash; the conceded halves of the family are better documented than the scored halves.")

E("fx_0918_f4.html",
  "<li><strong>Chelsea sold their deadline-day midfielder without replacing him and their remaining holder is a doubt.</strong> Enzo Fern&aacute;ndez went to Manchester City with the intended replacement &mdash; reported as Monaco's Lamine Camara, who plays in tonight's third fixture &mdash; not signed, Andrey Santos went for &pound;50m, and Ca&iuml;cedo has a calf problem. That is the single position on this card with the least cover and the most recent change.</li>",
  "<li><strong>Chelsea sold their deadline-day midfielder without replacing him and their remaining holder is now confirmed out.</strong> Enzo Fern&aacute;ndez went to Manchester City with the intended replacement &mdash; reported as Monaco's Lamine Camara, who starts in tonight's third fixture &mdash; not signed, Andrey Santos went for &pound;50m, Ca&iuml;cedo is out and Lavia is a substitute. <strong>The central midfield that takes the field is a 36-year-old signed from tonight's opponents and a 21-year-old signed from Strasbourg</strong>, which is the least-covered and most recently changed unit on this card.</li>")

E("fx_0918_f4.html",
  "<li><strong>The single fact that would most change which family I choose is whether Moises Ca&iuml;cedo starts.</strong> With Enzo Fern&aacute;ndez sold on deadline day and unreplaced and Andrey Santos gone for &pound;50m, Ca&iuml;cedo is the last first-choice holder at the club, and Chelsea's 1.95 xG conceded per match was accumulated with him available. A confirmed team sheet naming him, or not, would settle whether the conceded side of the BTTS and totals rows is the one the four-match sample measured &mdash; and it bears directly on the discipline row too, against a Brentford side committing 15.5 fouls a match.</li>",
  "<li><strong>That question is now answered: Ca&iuml;cedo does not play, and neither does Lavia from the start.</strong> Chelsea's 1.95 xG conceded per match was accumulated with Ca&iuml;cedo available, so the conceded side of the BTTS and totals rows is no longer the thing the four-match sample measured &mdash; which strengthens BTTS and weakens any read that depends on Chelsea conceding at their existing rate rather than above it. <strong>The one that replaces it: whether a 36-year-old central midfielder and a 21-year-old in a back-three system can hold possession against a press of 7.98 PPDA and 15.5 fouls a match under an official at 4.6 fouls per card.</strong> Nothing published settles that, and it is now the discipline row's largest single input.</li>")

# ---------------------------------------------------------------- f5
E("fx_0918_f5.html",
  "Espanyol foul more than anyone on the slate, Eder Sarabia is banned from the bench and the referee is making his seventh appearance in Primera</p>",
  "Espanyol foul more than anyone on the slate, Elche changed head coach in June, and the referee is making his fourth appearance in Primera</p>")

E("fx_0918_f5.html",
  "The structural headline is that this is <strong>the only fixture tonight in which both head coaches are the same men who finished last season &mdash; Manolo Gonz&aacute;lez at Espanyol and Eder Sarabia at Elche</strong> &mdash; and yet the squads underneath them turned over heavily, almost entirely through loans and purchase options rather than fees.",
  "The structural headline is a correction to what this card first said. <strong>Elche have changed head coach: Eder Sarabia announced on 27 May 2026 that he was stepping down &mdash; his own decision, to rest, not a dismissal &mdash; after taking the club up and keeping it up, and Mart&iacute;n Anselmi was appointed on 13 June 2026 on a one-year deal with an option.</strong> Anselmi is Argentine and arrives from a career at Cruz Azul, Porto and Botafogo. Only Manolo Gonz&aacute;lez is the man who finished last season, and the squads underneath both turned over heavily, almost entirely through loans and purchase options rather than fees. <strong>An earlier version of this card, built from a Spanish preview, named Sarabia as Elche&rsquo;s coach and reported him suspended from the bench; the confirmed team sheet names Anselmi and the club&rsquo;s own announcement dates the change to June. The preview was wrong and so was the card.</strong>")

E("fx_0918_f5.html",
  "<li><strong>Elche &mdash; turnover very high, funded by two large sales; Eder Sarabia continues but is suspended from the bench.</strong> <strong>No coaching change</strong>, though <strong>Sarabia cannot take his place on the touchline tonight through suspension</strong>.",
  "<li><strong>Elche &mdash; turnover very high, funded by two large sales; head coach changed 13 June 2026.</strong> <strong>Eder Sarabia stepped down of his own accord in late May and Mart&iacute;n Anselmi was announced on 13 June 2026</strong>, so the twelve arrivals below were assembled for a coach who had not worked in Spain before.")

E("fx_0918_f5.html",
  "<strong>Espanyol are without Jofre, Kike Garc&iacute;a and Javi Puado, all injured, with Gorosabel a doubt, and Omar El Hilali suspended for one match after being sent off against Rayo Vallecano</strong> &mdash; a red card taken three days ago, which is worth holding next to the card rates below. <strong>Elche's only confirmed injury absence is Yago Santiago</strong>, still recovering from a knee arthroscopy. <strong>Eder Sarabia is serving a touchline suspension and will not be on the bench.</strong> Probable elevens: <strong>Espanyol</strong> &mdash; Dmitrovi&#263;; Hartman, Riedel, Cabrera, Hinojo; Javi Hern&aacute;ndez, Exp&oacute;sito, Moscard&oacute;; Dolan, Zaragoza, Roberto Fern&aacute;ndez. <strong>Elche</strong> &mdash; Dituro; Sangar&eacute;, Chust, Redondo, Revivo; Valera, Aguado, Villar; Lemar, Buonanotte, Fer Ni&ntilde;o. Both probable back lines contain at least two players signed this summer.</li>",
  "<strong>Espanyol are without Javi Puado (knee), Kike Garc&iacute;a (hamstring) and Jofre Carreras (groin), and Omar El Hilali is suspended after his red card against Rayo Vallecano</strong> &mdash; a sending-off three days ago, which is worth holding next to the card rates below. <strong>Elche's only absence is Yago Santiago</strong>, still recovering from a knee arthroscopy &mdash; the shortest injury list on tonight's board. <strong>Confirmed elevens &mdash; Espanyol 4-2-3-1</strong>: Dmitrovi&#263;; Jes&uacute;s L&oacute;pez, Unai N&uacute;&ntilde;ez, Leandro Cabrera, Hinojo; Exp&oacute;sito, Javi Hern&aacute;ndez; Calatrava, Urko Gonz&aacute;lez, Zaragoza; Roberto Fern&aacute;ndez. <strong>Four of Espanyol&rsquo;s six summer loans are substitutes &mdash; Hartman, Moscard&oacute;, Drku&scaron;i&#263; and Dolan &mdash; so of the six, only Unai N&uacute;&ntilde;ez and Zaragoza start, and the &euro;5m Calatrava is the only bought player in the eleven.</strong> <strong>Elche 4-3-3</strong>: Dituro; Buba Sangar&eacute;, Federico Redondo, V&iacute;ctor Chust, Revivo; Germ&aacute;n Valera, Morcillo, Gonzalo Villar; Cepeda, Lemar, Fer Ni&ntilde;o &mdash; with <strong>Buonanotte, Ponce and Aguado on the bench</strong>. Nine of the twenty-two starters across the two teams arrived this summer.</li>")

E("fx_0918_f5.html",
  "<strong>One source disagreement to flag:</strong> a Spanish preview reached in the same search places this fixture at Elche's Mart&iacute;nez Valero and describes both clubs as winless in 2026. The venue in the official fixture record is the <strong>RCDE Stadium in Barcelona with Espanyol at home</strong>, the referee designation is published as &ldquo;RCD Espanyol &ndash; Elche CF&rdquo;, and Espanyol have two wins this season. That article is not used.</li>",
  "<strong>Two source failures to flag, one of which reached the card.</strong> A Spanish preview placed this fixture at Elche's Mart&iacute;nez Valero and called both clubs winless in 2026; the confirmed team sheet gives the venue as the <strong>RCDE Stadium in Barcelona</strong>, matching the fixture record and the referee designation, so that article is not used and the flag was right. <strong>The second failure did reach the card: the same preview cluster named Eder Sarabia as Elche's head coach and reported him suspended from the bench. He left in May. That error is corrected above rather than quietly removed, and it is the one place on this board where a card stated something false.</strong></li>")

E("fx_0918_f5.html",
  "<li><strong>The one normal fixture is Espanyol&ndash;Elche.</strong>",
  "<li><strong>Espanyol&ndash;Elche has the deepest sample.</strong>")

for fn, pairs in EDITS.items():
    s = io.open(fn, encoding="utf-8").read()
    for old, new in pairs:
        if old not in s:
            sys.exit("MISS in %s: %s..." % (fn, old[:90]))
        s = s.replace(old, new, 1)
    io.open(fn, "w", encoding="utf-8").write(s)
    print("patched %s (%d edits)" % (fn, len(pairs)))
